### PR TITLE
User can change subdomain of instance

### PR DESCRIPTION
**Pull request by katiejiang**
* Includes new new instances view
* Allows users to change subdomains, and updates Heroku and Cloudflare domains

**Cannot use already taken subdomain**

screen shot 2018-03-09 at 6 26 43 pm

**Update subdomain**

screen shot 2018-03-09 at 6 26 54 pm

**New instances view**

screen shot 2018-03-09 at 6 27 13 pm

### CODE REVIEW

**Comment by katiejiang** [comment]
@HanaPearlman @stephanieyshi Doesn't change the database so should be good to merge once it's reviewed

**Comment by HanaPearlman** [comment]
Looks great!! (a note is that I can't test this because of my cloudflare issue so waiting for @stephanieyshi )

**Comment by HanaPearlman** [comment]
Looks like there are still a few places in the code that reference the instances.manage_instances endpoint (which is now instances.view_instances) that need to be updated. Also there's a typo in app/instances/forms.py (the word descriptor is repeated) so it doesn't compile. And since there's a bug in the navbar there's now buggy navbar in this code too, so we might wanna wait until that is fixed :'(

**Comment by katiejiang** [comment]
Need to wait until the buggy navbar is fixed.

**Comment by stephanieyshi** [comment]
So the old domain doesn't work anymore but the new domain just gives me this error
image

**Comment by stephanieyshi** [comment]
wait update: it worked 😱so i'll add a comment that it will take a long time to update

**Review by stephanieyshi — APPROVED** [review]
LGTM!! going to merge this in now 😍

**Pull request merged**
